### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/html-album-cover#7]
Looks like the fonts on the lab are not loading. S3 issue?

See student's writeup of the problem: https://github.com/learn-co-students/html-album-cover-v-000/issues/367

@AnnJohn

**Comment by nsmmrs** [comment]
This is the result of a clumsy DRM policy that was implemented in non-Webkit browsers to help proprietary font vendors enforce their licensing.

As far as I can tell, there's actually nothing wrong on the school server's end. The problem is that all students are opening the website on their local environment. Since the DRM is client-side, it can be disabled on the student's end, [but only by disabling their browser's security with the command line.](https://productforums.google.com/forum/#!topic/chrome/9nHBcjNW384) Probably a bad idea, but I tried it and it indeed solves the font-display issue.

My two cents: use Google Fonts instead (or The League of Moveable Type, or some other truly free web font repository), like CodeCademy does. This will save Learn.co whatever money currently goes into licensing proprietary fonts, and would just make stylistic sense for a company that embraces Open Source the way Learn.co does.

**Comment by kwebster2** [comment]
@cjbrock It looks like this is still an issue. #12 might address this.

**Comment by maxwellbenton** [comment]
Thank you all for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
